export const BASE_CODE_NUMBER = 1001;
export enum ErrorCode {
  SUCCESS = 'SUCCESS',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NO_PERMISSION = 'NO_PERMISSION',
  INVALID_PARAMS = 'INVALID_PARAMS',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INPOSSIBLE_PHONE_NUMBER = 'INPOSSIBLE_PHONE_NUMBER',
  INVALID_PHONE_COUNTRY = 'INVALID_PHONE_COUNTRY',
  EMPTY_PARAMS = 'EMPTY_PARAMS',
  TOO_MANY_REQUEST = 'TOO_MANY_REQUEST',

  // auth
  INVALID_CAPTCHA_CODE = 'INVALID_CAPTCHA_CODE',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  // user
  USER_USERNAME_OR_PASSWORD_INCORRECT = 'USER_USERNAME_OR_PASSWORD_INCORRECT',
  USER_LOGIN_FAIL = 'USER_LOGIN_FAIL',
  USER_REGISTER_FAIL = 'USER_REGISTER_FAIL',
  USER_UPDATE_FAIL = 'USER_UPDATE_FAIL',
  USER_EXIST = 'USER_EXIST',
  USER_NOT_EXIST = 'USER_NOT_EXIST',
  USER_HAS_BEEN_BLOCKED = 'USER_HAS_BEEN_BLOCKED',
  // role
  ROLE_EXIST = 'ROLE_EXIST',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_CREATE_FAIL = 'ROLE_CREATE_FAIL',
  REDIS_COMMAND_FAIL = 'REDIS_COMMAND_FAIL',

  // admin
  ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL',
  ADMIN_DELETE_FAIL = 'ADMIN_DELETE_FAIL',
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',

  // file
  FILE_TYPE_ERROR = 'FILE_TYPE_ERROR',
  IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL',
  IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
  IMAGE_SAVE_ERROR = 'IMAGE_SAVE_ERROR',
  IMAGE_HASH_ERROR = 'IMAGE_HASH_ERROR',

  // league
  LEAGUE_NOT_FOUND = 'LEAGUE_NOT_FOUND',
  LEAGUE_NOT_HAS_LEAGUETABLE = 'LEAGUE_NOT_HAS_LEAGUETABLE',
  LEAGUE_NOT_HAS_TOPLIST = 'LEAGUE_NOT_HAS_TOPLIST',

  // SMS
  SMS_TOKEN_INVALID = 'SMS_TOKEN_INVALID',
  SMS_TOKEN_REMAIN_TIMES_NOT_ENOUGH = 'SMS_TOKEN_REMAIN_TIMES_NOT_ENOUGH',
  SMS_RATE_LIMIT = 'SMS_RATE_LIMIT',
}
